import java.math.BigInteger;
import java.security.MessageDigest;
class sha1{
	public static void main(String[] args) throws Exception{
		try{
		String input="hello world";
		MessageDigest md=MessageDigest.getInstance("SHA-1");
		byte[] messageDigest=md.digest(input.getBytes());
		BigInteger no=new BigInteger(1,messageDigest);
		String hashtext=no.toString(16);
		System.out.println("hashtext generated by SHA-1 for "+ input + " : "+hashtext);
		}
		catch(Exception e){}
	}
}
